CRITICAL - 2022-06-09 05:10:47 --> Invalid file: artikel.php
#0 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('artikel.php')
#1 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\Common.php(1089): CodeIgniter\View\View->render('artikel', Array, true)
#2 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\app\Controllers\page.php(11): view('artikel', Array)
#3 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\CodeIgniter.php(832): App\Controllers\Page->artikel()
#4 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Page))
#5 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-06-09 05:13:30 --> Invalid file: artikel.php
#0 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('artikel.php')
#1 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\Common.php(1089): CodeIgniter\View\View->render('artikel', Array, true)
#2 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\app\Controllers\page.php(11): view('artikel', Array)
#3 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\CodeIgniter.php(832): App\Controllers\Page->artikel()
#4 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Page))
#5 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-06-09 05:20:11 --> Invalid file: artikel.php
#0 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('artikel.php')
#1 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\Common.php(1089): CodeIgniter\View\View->render('artikel', Array, true)
#2 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\app\Controllers\page.php(11): view('artikel', Array)
#3 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\CodeIgniter.php(832): App\Controllers\Page->artikel()
#4 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Page))
#5 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
ERROR - 2022-06-09 05:22:26 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-06-09 05:22:26 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\app\Controllers\Artikel.php(13): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\CodeIgniter.php(832): App\Controllers\Artikel->index()
#6 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Artikel))
#7 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
ERROR - 2022-06-09 05:22:51 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-06-09 05:22:51 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\app\Controllers\Artikel.php(13): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\CodeIgniter.php(832): App\Controllers\Artikel->index()
#6 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Artikel))
#7 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
ERROR - 2022-06-09 05:23:06 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-06-09 05:23:06 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\app\Controllers\Artikel.php(13): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\CodeIgniter.php(832): App\Controllers\Artikel->index()
#6 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Artikel))
#7 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Lab11web\lab11_php_ci\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
